import type { OrdemServico } from "./OrdensServico";

const PLACEHOLDER_FOTO = "https://placehold.co/300x200";

export const OS_MOCKS: OrdemServico[] = [
  {
    id: "1",
    numeroOS: "OS-2025-001",
    cliente: {
      id: "c1",
      nome: "Restaurante Bom Sabor",
      cpfCnpj: "12.345.678/0001-90",
      telefone: "11987654321",
    },
    tipoServico: "controle_pragas_vetores",
    tecnicoId: "t1",
    tecnicoNome: "Carlos Silva",
    dataAgendamento: new Date("2025-01-15"),
    horaAgendamento: "09:00",
    endereco: "Rua das Flores, 123 - Sao Paulo/SP",
    status: "concluida",
    observacoes: "Cliente solicitou prioridade na cozinha e deposito.",
    dataConclusao: new Date("2025-01-15"),
    valorServico: 450,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosDepois: [
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
    ],
    diagnosticoLocal: {
      pragasAlvo: ["Baratas", "Formigas"],
      areaExterna: "Quintal com lixeira coletiva",
      areaVicinal: "Restaurantes vizinhos",
      pontoDeReferencia: "Proximo ao mercado municipal",
      piscina: false,
      pet: true,
    },
    dadosProduto: {
      controlePragasVetores: [
        {
          id: "os1-cpv-1",
          principioAtivo: "Cipermetrina",
          concentracao: "25%",
          diluente: "Agua",
          volume: "5L",
          setor: "Cozinha",
          equipamento: "Pulverizador costal",
        },
        {
          id: "os1-cpv-2",
          principioAtivo: "Fipronil",
          concentracao: "0,05%",
          diluente: "Gel",
          volume: "500g",
          setor: "Deposito",
          equipamento: "Aplicador manual",
        },
      ],
    },
    vistoria: [
      {
        id: "os1-vistoria-1",
        setor: "Cozinha",
        situacao: "Presenca de baratas em frestas",
        medidaCorretiva: "Aplicacao de gel inseticida",
        avaliacao: "Infestacao moderada",
      },
      {
        id: "os1-vistoria-2",
        setor: "Deposito",
        situacao: "Formigas em embalagens",
        medidaCorretiva: "Iscas granuladas",
        avaliacao: "Infestacao leve",
      },
    ],
    descricaoServico: [
      {
        id: "os1-descricao-1",
        setor: "Cozinha",
        higieneLocal: "Regular",
        nivelInfestacao: "Moderado",
        equipamento: "Pulverizador costal",
      },
      {
        id: "os1-descricao-2",
        setor: "Deposito",
        higieneLocal: "Bom",
        nivelInfestacao: "Leve",
        equipamento: "Aplicador manual",
      },
    ],
  },
  {
    id: "2",
    numeroOS: "OS-2025-002",
    cliente: {
      id: "c2",
      nome: "Padaria Pao Quente",
      cpfCnpj: "98.765.432/0001-10",
      telefone: "11912345678",
    },
    tipoServico: "higienizacao",
    tecnicoId: "t2",
    tecnicoNome: "Joao Santos",
    dataAgendamento: new Date("2025-01-16"),
    horaAgendamento: "14:00",
    endereco: "Av. Principal, 456 - Sao Paulo/SP",
    status: "em_andamento",
    observacoes: "Reservatorio no terraco, acesso por escada estreita.",
    valorServico: 300,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosDepois: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Mosquitos"],
      areaExterna: "Calcada com drenagem",
      areaVicinal: "Area comercial",
      pontoDeReferencia: "Em frente a praca central",
      piscina: false,
      pet: false,
    },
    dadosProduto: {
      higienizacao: {
        tipoEquipamento: "Bomba submersivel",
        nivelChuva: "Baixo",
        tempoDuracaoEstimado: 180,
        volume: 5000,
        realizarColeta: true,
        fecharRegistro: true,
      },
    },
    reservatorios: [
      {
        id: "os2-reservatorio-1",
        reservatorio: "Caixa d'agua principal",
        material: "Concreto",
        volume: 5000,
        desinfeccao: 150,
        situacao: "Sedimentos visiveis",
        vetores: false,
        residuos: true,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Desgastada",
        pintura: "Desbotada",
        revestimentoInterno: "Sem revestimento",
        sistemaDeLadrao: "Funcional",
      },
      {
        id: "os2-reservatorio-2",
        reservatorio: "Caixa auxiliar",
        material: "Polietileno",
        volume: 1000,
        desinfeccao: 30,
        situacao: "Bom estado",
        vetores: false,
        residuos: false,
        fendas: true,
        boia: "Com defeito",
        cobertura: "Boa",
        pintura: "Conservada",
        revestimentoInterno: "Epoxi",
        sistemaDeLadrao: "Funcional",
      },
    ],
    descricaoServico: [
      {
        id: "os2-descricao-1",
        setor: "Terraco",
        higieneLocal: "Regular",
        nivelInfestacao: "N/A",
        equipamento: "Bomba submersivel",
      },
    ],
    vistoria: [
      {
        id: "os2-vistoria-1",
        setor: "Terraco",
        situacao: "Tampa com desgaste",
        medidaCorretiva: "Substituir vedacao",
        avaliacao: "Manutencao recomendada",
      },
    ],
  },
  {
    id: "3",
    numeroOS: "OS-2025-003",
    cliente: {
      id: "c3",
      nome: "Supermercado Central",
      cpfCnpj: "11.222.333/0001-44",
      telefone: "11999887766",
    },
    tipoServico: "sanitizacao",
    tecnicoId: "t1",
    tecnicoNome: "Carlos Silva",
    dataAgendamento: new Date("2025-01-17"),
    horaAgendamento: "08:00",
    endereco: "Rua do Comercio, 789 - Sao Paulo/SP",
    status: "agendada",
    observacoes: "Servico apos horario de fechamento, a partir das 22h.",
    valorServico: 1200,
    fotos: [
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
      PLACEHOLDER_FOTO,
    ],
    diagnosticoLocal: {
      pragasAlvo: ["Virus", "Bacterias"],
      areaExterna: "Estacionamento",
      areaVicinal: "Centro comercial",
      pontoDeReferencia: "Ao lado do terminal de onibus",
      piscina: false,
      pet: false,
    },
    dadosProduto: {
      sanitizacao: {
        principioAtivo: "Quaternario de amonio",
        produto: "Sanitizante multiuso",
        diluente: "Agua",
        volume: "20L",
        setor: "Salao de vendas",
        equipamento: "Nebulizador ULV",
      },
    },
    vistoria: [
      {
        id: "os3-vistoria-1",
        setor: "Salao de vendas",
        situacao: "Superficies de alto contato",
        medidaCorretiva: "Sanitizacao completa",
        avaliacao: "Conforme protocolo",
      },
    ],
    descricaoServico: [
      {
        id: "os3-descricao-1",
        setor: "Salao de vendas",
        higieneLocal: "Bom",
        nivelInfestacao: "N/A",
        equipamento: "Nebulizador ULV",
      },
    ],
  },
  {
    id: "4",
    numeroOS: "OS-2025-004",
    cliente: {
      id: "c4",
      nome: "Ana Oliveira",
      cpfCnpj: "00000000000",
      telefone: "11000000000",
    },
    tipoServico: "monitoramento_insetos",
    tecnicoId: "t3",
    tecnicoNome: "Pedro Costa",
    dataAgendamento: new Date("2025-01-18"),
    horaAgendamento: "10:00",
    endereco: "Rua das Palmeiras, 321 - Sao Paulo/SP",
    status: "agendada",
    observacoes: "Primeira vistoria de monitoramento, 12 pontos mapeados.",
    valorServico: 350,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO],
    fotosDepois: [PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Moscas", "Baratas"],
      areaExterna: "Jardim",
      areaVicinal: "Condominio residencial",
      pontoDeReferencia: "Portaria principal",
      piscina: true,
      pet: true,
    },
    monitoramento: [
      {
        id: "os4-monitoramento-1",
        areaMonitorada: "Cozinha",
        pragaAlvo: ["Baratas"],
        tratamento: "Gel inseticida",
        grauInfestacao: "Leve",
        produtoUtilizado: "Gel baraticida",
        adesiva: "Armadilha adesiva A1",
        produto: "Gel baraticida",
        ml: 15,
        refilLuminosa: false,
        quantidade: 2,
        fotos: [PLACEHOLDER_FOTO],
        observacoes: "Ponto proximo a pia",
      },
      {
        id: "os4-monitoramento-2",
        areaMonitorada: "Area externa",
        pragaAlvo: ["Moscas"],
        tratamento: "Armadilha luminosa",
        grauInfestacao: "Moderado",
        produtoUtilizado: "Refil adesivo",
        adesiva: "Armadilha adesiva B2",
        produto: "Refil adesivo",
        ml: 0,
        refilLuminosa: true,
        quantidade: 1,
        fotos: [PLACEHOLDER_FOTO],
        observacoes: "Proximo a lixeira",
      },
    ],
    descricaoServico: [
      {
        id: "os4-descricao-1",
        setor: "Cozinha",
        higieneLocal: "Bom",
        nivelInfestacao: "Leve",
        equipamento: "Armadilha adesiva",
      },
    ],
  },
  {
    id: "5",
    numeroOS: "OS-2025-005",
    cliente: {
      id: "c5",
      nome: "Hotel Descanso",
      cpfCnpj: "55.666.777/0001-88",
      telefone: "13988776655",
    },
    tipoServico: "monitoramento_roedores",
    tecnicoId: "t2",
    tecnicoNome: "Joao Santos",
    dataAgendamento: new Date("2025-01-14"),
    horaAgendamento: "15:00",
    endereco: "Av. Turistica, 999 - Guaruja/SP",
    status: "cancelada",
    observacoes: "Cancelado a pedido do cliente por reforma no local.",
    valorServico: 800,
    fotos: [PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Ratos", "Camundongos"],
      areaExterna: "Jardim e estacionamento",
      areaVicinal: "Orla da praia",
      pontoDeReferencia: "Entrada lateral do hotel",
      piscina: true,
      pet: false,
    },
    estacoes: [
      {
        id: "os5-estacao-1",
        nome: "Estacao principal - subsolo",
        portaIscaRaticida: ["isca_consumida", "isca_danificada", "isca_extraviada"],
        armadilhaAdesiva: ["cola_danificada", "porta_adesivo_quebrado", "porta_adesivo_extraviado"],
        controle: [
          { id: "os5-controle-1", produto: "Raticida bloco parafinado", quantidade: 3 },
          { id: "os5-controle-2", produto: "Gel rodenticida", quantidade: 2 },
        ],
        pontosVariaveis: [
          {
            id: "os5-ponto-1",
            local: "Cozinha industrial",
            produto: "Raticida bloco",
            quantidade: 2,
          },
          { id: "os5-ponto-2", local: "Deposito", produto: "Armadilha adesiva", quantidade: 4 },
        ],
        fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
        observacoes:
          "Servico realizado com sucesso, todas as estacoes foram instaladas e configuradas conforme o protocolo.",
      },
      {
        id: "os5-estacao-2",
        nome: "Estacao secundaria - cobertura",
        portaIscaRaticida: ["isca_consumida", "isca_danificada", "isca_extraviada"],
        armadilhaAdesiva: ["cola_danificada", "porta_adesivo_quebrado", "em_conformidade"],
        controle: [
          { id: "os5-controle-3", produto: "Raticida bloco parafinado", quantidade: 3 },
          { id: "os5-controle-4", produto: "Gel rodenticida", quantidade: 2 },
        ],
        pontosVariaveis: [
          {
            id: "os5-ponto-3",
            local: "Sala de reunioes",
            produto: "Raticida bloco",
            quantidade: 2,
          },
          {
            id: "os5-ponto-790",
            local: "Cozinha industrial",
            produto: "Gel rodenticida",
            quantidade: 56,
          },
          { id: "os5-ponto-4", local: "Biblioteca", produto: "Armadilha adesiva", quantidade: 4 },
        ],
        fotos: [
          PLACEHOLDER_FOTO,
          PLACEHOLDER_FOTO,
          PLACEHOLDER_FOTO,
          PLACEHOLDER_FOTO,
          PLACEHOLDER_FOTO,
          PLACEHOLDER_FOTO,
        ],
        observacoes:
          "Servico realizado com sucesso, todas as estacoes foram instaladas e configuradas conforme o protocolo.",
      },
    ],
    vistoria: [
      {
        id: "os5-vistoria-1",
        setor: "Subsolo",
        situacao: "Fezes identificadas",
        medidaCorretiva: "Instalacao de estacoes",
        avaliacao: "Infestacao moderada",
      },
    ],
  },
  {
    id: "6",
    numeroOS: "OS-2025-006",
    cliente: {
      id: "c6",
      nome: "Condominio Vila Verde",
      cpfCnpj: "22.333.444/0001-55",
      telefone: "11955443322",
    },
    tipoServico: "higienizacao",
    tecnicoId: "t1",
    tecnicoNome: "Carlos Silva",
    dataAgendamento: new Date("2025-01-20"),
    horaAgendamento: "07:30",
    endereco: "Rua dos Ipes, 150 - Santo Andre/SP",
    status: "concluida",
    observacoes: "Limpeza anual dos reservatorios das torres A e B concluida sem intercorrencias.",
    dataConclusao: new Date("2025-01-20"),
    valorServico: 2800,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosDepois: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Mosquitos", "Baratas"],
      areaExterna: "Jardim e garagem",
      areaVicinal: "Condominio residencial",
      pontoDeReferencia: "Portaria da torre A",
      piscina: true,
      pet: true,
    },
    dadosProduto: {
      higienizacao: {
        tipoEquipamento: "Bomba submersivel",
        nivelChuva: "Medio",
        tempoDuracaoEstimado: 360,
        volume: 12000,
        realizarColeta: true,
        fecharRegistro: true,
      },
    },
    reservatorios: [
      {
        id: "os6-reservatorio-1",
        reservatorio: "Torre A - Caixa superior",
        material: "Concreto",
        volume: 6000,
        desinfeccao: 180,
        situacao: "Sedimentos moderados",
        vetores: false,
        residuos: true,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Boa",
        pintura: "Conservada",
        revestimentoInterno: "Epoxi",
        sistemaDeLadrao: "Funcional",
      },
      {
        id: "os6-reservatorio-2",
        reservatorio: "Torre A - Caixa inferior",
        material: "Concreto",
        volume: 6000,
        desinfeccao: 180,
        situacao: "Bom estado",
        vetores: false,
        residuos: false,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Boa",
        pintura: "Conservada",
        revestimentoInterno: "Epoxi",
        sistemaDeLadrao: "Funcional",
      },
      {
        id: "os6-reservatorio-3",
        reservatorio: "Torre B - Caixa superior",
        material: "Fibra de vidro",
        volume: 4000,
        desinfeccao: 120,
        situacao: "Algas leves",
        vetores: true,
        residuos: true,
        fendas: true,
        boia: "Com defeito",
        cobertura: "Desgastada",
        pintura: "Desbotada",
        revestimentoInterno: "Ceramica",
        sistemaDeLadrao: "Obstruido",
      },
      {
        id: "os6-reservatorio-4",
        reservatorio: "Torre B - Caixa inferior",
        material: "Fibra de vidro",
        volume: 4000,
        desinfeccao: 120,
        situacao: "Necessita manutencao",
        vetores: false,
        residuos: true,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Regular",
        pintura: "Sem pintura",
        revestimentoInterno: "Sem revestimento",
        sistemaDeLadrao: "Funcional",
      },
    ],
    vistoria: [
      {
        id: "os6-vistoria-1",
        setor: "Torre A",
        situacao: "Tampas com vedacao adequada",
        medidaCorretiva: "Manter periodicidade semestral",
        avaliacao: "Conforme",
      },
      {
        id: "os6-vistoria-2",
        setor: "Torre B",
        situacao: "Infiltracao leve na tampa",
        medidaCorretiva: "Reforcar vedacao e pintura",
        avaliacao: "Manutencao recomendada",
      },
    ],
    descricaoServico: [
      {
        id: "os6-descricao-1",
        setor: "Torre A",
        higieneLocal: "Bom",
        nivelInfestacao: "N/A",
        equipamento: "Bomba submersivel",
      },
      {
        id: "os6-descricao-2",
        setor: "Torre B",
        higieneLocal: "Regular",
        nivelInfestacao: "N/A",
        equipamento: "Bomba submersivel",
      },
    ],
  },
  {
    id: "7",
    numeroOS: "OS-2025-007",
    cliente: {
      id: "c7",
      nome: "Clinica Sorriso",
      cpfCnpj: "33.444.555/0001-66",
      telefone: "11966778899",
    },
    tipoServico: "higienizacao",
    tecnicoId: "t3",
    tecnicoNome: "Pedro Costa",
    dataAgendamento: new Date("2025-01-22"),
    horaAgendamento: "06:00",
    endereco: "Av. Paulista, 1200 - Sao Paulo/SP",
    status: "agendada",
    observacoes: "Servico deve iniciar antes do horario de atendimento, as 06h.",
    valorServico: 950,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Bacterias"],
      areaExterna: "Calcada",
      areaVicinal: "Centro comercial",
      pontoDeReferencia: "Proximo ao metro Trianon",
      piscina: false,
      pet: false,
    },
    dadosProduto: {
      higienizacao: {
        tipoEquipamento: "Bomba submersivel",
        nivelChuva: "Baixo",
        tempoDuracaoEstimado: 120,
        volume: 3000,
        realizarColeta: true,
        fecharRegistro: true,
      },
    },
    reservatorios: [
      {
        id: "os7-reservatorio-1",
        reservatorio: "Caixa d'agua - 5o andar",
        material: "Polietileno",
        volume: 3000,
        desinfeccao: 90,
        situacao: "Bom estado",
        vetores: false,
        residuos: false,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Boa",
        pintura: "Conservada",
        revestimentoInterno: "Epoxi",
        sistemaDeLadrao: "Funcional",
      },
      {
        id: "os7-reservatorio-2",
        reservatorio: "Caixa d'agua - cobertura",
        material: "Polietileno",
        volume: 1500,
        desinfeccao: 45,
        situacao: "Regular",
        vetores: false,
        residuos: false,
        fendas: true,
        boia: "Nao possui",
        cobertura: "Regular",
        pintura: "Desbotada",
        revestimentoInterno: "Sem revestimento",
        sistemaDeLadrao: "Nao possui",
      },
      {
        id: "os7-reservatorio-3",
        reservatorio: "Reservatorio de reserva",
        material: "Concreto",
        volume: 2000,
        desinfeccao: 60,
        situacao: "Pouco utilizado",
        vetores: false,
        residuos: false,
        fendas: false,
        boia: "Funcionando",
        cobertura: "Boa",
        pintura: "Conservada",
        revestimentoInterno: "Ceramica",
        sistemaDeLadrao: "Funcional",
      },
    ],
    vistoria: [
      {
        id: "os7-vistoria-1",
        setor: "Cobertura",
        situacao: "Acesso restrito por escada",
        medidaCorretiva: "Agendar com antecedencia",
        avaliacao: "Planejado",
      },
    ],
    descricaoServico: [
      {
        id: "os7-descricao-1",
        setor: "Cobertura",
        higieneLocal: "Bom",
        nivelInfestacao: "N/A",
        equipamento: "Bomba submersivel",
      },
    ],
  },
  {
    id: "8",
    numeroOS: "OS-2025-008",
    cliente: {
      id: "c8",
      nome: "Industria MetalTech",
      cpfCnpj: "44.555.666/0001-77",
      telefone: "11977889900",
    },
    tipoServico: "controle_pragas_vetores",
    tecnicoId: "t2",
    tecnicoNome: "Joao Santos",
    dataAgendamento: new Date("2025-01-21"),
    horaAgendamento: "18:00",
    endereco: "Rod. Anhanguera, km 42 - Jundiai/SP",
    status: "em_andamento",
    observacoes: "Aplicacao noturna no galpao de producao e refeitorio.",
    valorServico: 1850,
    fotos: [PLACEHOLDER_FOTO, PLACEHOLDER_FOTO],
    fotosAntes: [PLACEHOLDER_FOTO],
    fotosDepois: [PLACEHOLDER_FOTO],
    diagnosticoLocal: {
      pragasAlvo: ["Baratas", "Roedores", "Formigas"],
      areaExterna: "Patio de carga",
      areaVicinal: "Distrito industrial",
      pontoDeReferencia: "Entrada do galpao 3",
      piscina: false,
      pet: false,
    },
    dadosProduto: {
      controlePragasVetores: [
        {
          id: "os8-cpv-1",
          principioAtivo: "Cipermetrina",
          concentracao: "25%",
          diluente: "Agua",
          volume: "10L",
          setor: "Galpao de producao",
          equipamento: "Pulverizador costal",
        },
        {
          id: "os8-cpv-2",
          principioAtivo: "Brodifacoum",
          concentracao: "0,005%",
          diluente: "Isca",
          volume: "2kg",
          setor: "Refeitorio",
          equipamento: "Porta isca",
        },
      ],
    },
    vistoria: [
      {
        id: "os8-vistoria-1",
        setor: "Galpao de producao",
        situacao: "Baratas em maquinario",
        medidaCorretiva: "Gel inseticida e iscas",
        avaliacao: "Infestacao moderada",
      },
      {
        id: "os8-vistoria-2",
        setor: "Refeitorio",
        situacao: "Fezes de roedores",
        medidaCorretiva: "Instalacao de estacoes",
        avaliacao: "Infestacao leve",
      },
    ],
    descricaoServico: [
      {
        id: "os8-descricao-1",
        setor: "Galpao de producao",
        higieneLocal: "Regular",
        nivelInfestacao: "Moderado",
        equipamento: "Pulverizador costal",
      },
      {
        id: "os8-descricao-2",
        setor: "Refeitorio",
        higieneLocal: "Bom",
        nivelInfestacao: "Leve",
        equipamento: "Porta isca",
      },
    ],
  },
];
