import type { Cliente } from "@/model/rest/cliente";

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "cliente-1",
    nomeRazaoSocial: "Restaurante Bom Sabor",
    cnpjCpf: "12.345.678/0001-90",
    tipo: "RECORRENTE",
    email: "contato@bomsabor.com",
    telefone: "(11) 3456-7890",
    status: "ATIVO",
    dataUltimoServico: "2025-12-10",
    enderecos: [
      {
        rua: "Rua das Flores",
        numero: "123",
        complemento: "",
        bairro: "",
        cidade: "Sao Paulo",
        estado: "SP",
        cep: "01310-100",
      },
    ],
  },
  {
    id: "cliente-2",
    nomeRazaoSocial: "Padaria Pao Quente",
    cnpjCpf: "98.765.432/0001-10",
    tipo: "RECORRENTE",
    email: "gerencia@paoquente.com",
    telefone: "(11) 2345-6789",
    status: "ATIVO",
    dataUltimoServico: "2026-01-05",
    enderecos: [
      {
        rua: "Av. Principal",
        numero: "456",
        complemento: "",
        bairro: "",
        cidade: "Sao Paulo",
        estado: "SP",
        cep: "04567-000",
      },
    ],
  },
  {
    id: "cliente-3",
    nomeRazaoSocial: "Supermercado Central",
    cnpjCpf: "11.222.333/0001-44",
    tipo: "RECORRENTE",
    email: "compras@supercentral.com.br",
    telefone: "(21) 3567-8901",
    status: "ATIVO",
    dataUltimoServico: "2025-11-28",
    enderecos: [
      {
        rua: "Rua do Comercio",
        numero: "789",
        complemento: "",
        bairro: "",
        cidade: "Rio de Janeiro",
        estado: "RJ",
        cep: "20040-020",
      },
    ],
  },
  {
    id: "cliente-4",
    nomeRazaoSocial: "Ana Oliveira",
    cnpjCpf: "123.456.789-00",
    tipo: "ESPORADICO",
    email: "ana.oliveira@email.com",
    telefone: "(31) 98765-4321",
    status: "ATIVO",
    enderecos: [
      {
        rua: "Rua das Palmeiras",
        numero: "321",
        complemento: "",
        bairro: "",
        cidade: "Belo Horizonte",
        estado: "MG",
        cep: "30130-110",
      },
    ],
  },
  {
    id: "cliente-5",
    nomeRazaoSocial: "Hotel Descanso",
    cnpjCpf: "55.666.777/0001-88",
    tipo: "RECORRENTE",
    email: "reservas@hoteldescanso.com",
    telefone: "(48) 3344-5566",
    observacoes: "Contrato encerrado em ago/2024.",
    status: "INATIVO",
    dataUltimoServico: "2024-08-15",
    enderecos: [
      {
        rua: "Av. Beira Mar",
        numero: "100",
        complemento: "",
        bairro: "",
        cidade: "Florianopolis",
        estado: "SC",
        cep: "88015-700",
      },
    ],
  },
  {
    id: "cliente-6",
    nomeRazaoSocial: "Industria MetalTech",
    cnpjCpf: "44.555.666/0001-77",
    tipo: "RECORRENTE",
    email: "roberto@metaltech.com.br",
    telefone: "(19) 94321-0987",
    status: "ATIVO",
    dataUltimoServico: "2026-02-01",
    enderecos: [
      {
        rua: "Rod. Anhanguera, km 42",
        numero: "",
        complemento: "",
        bairro: "",
        cidade: "Campinas",
        estado: "SP",
        cep: "13050-000",
      },
    ],
  },
  {
    id: "cliente-7",
    nomeRazaoSocial: "Carlos Mendes",
    cnpjCpf: "987.654.321-00",
    tipo: "ESPORADICO",
    email: "carlos.mendes@email.com",
    telefone: "(41) 96543-2109",
    status: "ATIVO",
    enderecos: [
      {
        rua: "Rua XV de Novembro",
        numero: "50",
        complemento: "",
        bairro: "",
        cidade: "Curitiba",
        estado: "PR",
        cep: "80020-310",
      },
    ],
  },
  {
    id: "cliente-8",
    nomeRazaoSocial: "Escola Futuro Brilhante",
    cnpjCpf: "33.444.555/0001-66",
    tipo: "RECORRENTE",
    email: "administracao@futurobrilhante.edu.br",
    telefone: "(51) 3322-1100",
    status: "ATIVO",
    dataUltimoServico: "2025-10-20",
    enderecos: [
      {
        rua: "Rua das Acacias",
        numero: "200",
        complemento: "",
        bairro: "",
        cidade: "Porto Alegre",
        estado: "RS",
        cep: "90010-000",
      },
    ],
  },
  {
    id: "cliente-9",
    nomeRazaoSocial: "Fernanda Lima",
    cnpjCpf: "456.789.123-45",
    tipo: "ESPORADICO",
    email: "fernanda.lima@email.com",
    telefone: "(85) 98888-7777",
    status: "INATIVO",
    enderecos: [
      {
        rua: "Av. Beira Mar",
        numero: "1500",
        complemento: "",
        bairro: "",
        cidade: "Fortaleza",
        estado: "CE",
        cep: "60165-121",
      },
    ],
  },
  {
    id: "cliente-10",
    nomeRazaoSocial: "Clinica Vida Saudavel",
    cnpjCpf: "22.333.444/0001-55",
    tipo: "RECORRENTE",
    email: "contato@vidasaudavel.com.br",
    telefone: "(62) 3210-9876",
    status: "ATIVO",
    dataUltimoServico: "2026-01-15",
    enderecos: [
      {
        rua: "Rua 10, Quadra 5",
        numero: "",
        complemento: "",
        bairro: "",
        cidade: "Goiania",
        estado: "GO",
        cep: "74000-000",
      },
    ],
  },
];
