/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/usuarios/editar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edita um usuário existente. @ADMINISTRATIVO */
        put: operations["editar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém detalhes de um lead pelo ID
         * @description Obtém detalhes de um lead específico
         */
        get: operations["obterPorId"];
        /**
         * Edita um lead existente
         * @description Edita todas as informações de um lead
         */
        put: operations["editar_1"];
        post?: never;
        /**
         * Exclui um lead
         * @description Exclui um lead permanentemente
         */
        delete: operations["excluir"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém detalhes de um cliente pelo ID
         * @description Obtém todos os dados cadastrais do cliente
         */
        get: operations["obterPorId_1"];
        /**
         * Edita um cliente existente
         * @description Edita todas as informações cadastrais do cliente
         */
        put: operations["editar_2"];
        post?: never;
        /**
         * Exclui um cliente
         * @description Exclui um cliente permanentemente
         */
        delete: operations["excluir_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/redefinir-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Muda a senha do usuário */
        post: operations["redefinirSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout do usuário
         * @description Revoga o token JWT atual
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chamada para usuário logar no sistema
         * @description Chamada para usuário logar no sistema
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/cadastrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cadastra um novo usuário. @ADMINISTRATIVO */
        post: operations["cadastrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém lista paginada de leads
         * @description Retorna lista de leads paginada e com filtros
         */
        get: operations["obterTodos"];
        put?: never;
        /**
         * Cadastra um novo lead
         * @description Cadastra um novo lead no funil de vendas
         */
        post: operations["cadastrar_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém uma lista paginada de clientes
         * @description Retorna lista de clientes paginada e com filtros
         */
        get: operations["obterTodos_1"];
        put?: never;
        /**
         * Cadastra um novo cliente
         * @description Cadastra um novo cliente e seus endereços e documentos
         */
        post: operations["cadastrar_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza o status do lead
         * @description Atualiza o status na esteira do Kanban
         */
        patch: operations["atualizarStatus"];
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém uma lista paginada de usuários. @ADMINISTRATIVO */
        get: operations["obterTodosUsuarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtém detalhes de um usuário pelo ID. @ADMINISTRATIVO */
        get: operations["obterUsuarioPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém as métricas gerais dos leads
         * @description Retorna os dados numéricos consolidados do dashboard
         */
        get: operations["obterDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtém as métricas gerais do dashboard de clientes
         * @description Retorna dados numéricos de clientes ativos, fixos, esporádicos e total
         */
        get: operations["obterDashboard_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/excluir/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui um usuário. @ADMINISTRATIVO */
        delete: operations["excluir_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EditarUsuarioInputDTO: {
            nomeCompleto?: string;
            email?: string;
            cpf?: string;
            senha?: string;
            /** @enum {string} */
            perfil: "ADMINISTRATIVO" | "TECNICO" | "CLIENTE";
            /** @enum {string} */
            status: "ATIVO" | "INATIVO";
        };
        UsuarioResponseDTO: {
            /** Format: uuid */
            id: string;
            nomeCompleto: string;
            email: string;
            /** @enum {string} */
            status: "ATIVO" | "INATIVO";
            /** @enum {string} */
            perfil: "ADMINISTRATIVO" | "TECNICO" | "CLIENTE";
            cpf?: string;
        };
        EditarLeadInputDTO: {
            nome?: string;
            empresa?: string;
            email?: string;
            telefone?: string;
            /** @enum {string} */
            origem: "GOOGLE" | "FACEBOOK" | "INSTAGRAM" | "WEBSITE" | "INDICACAO" | "OUTRO";
            valorEstimado: number;
            /** @enum {string} */
            status: "NOVO" | "EM_CONTATO" | "PROPOSTA_ENVIADA" | "EM_NEGOCIACAO" | "GANHO" | "PERDIDO";
            observacoes?: string;
        };
        LeadResponseDTO: {
            /** Format: uuid */
            id?: string;
            nome?: string;
            empresa?: string;
            email?: string;
            telefone?: string;
            /** @enum {string} */
            origem?: "GOOGLE" | "FACEBOOK" | "INSTAGRAM" | "WEBSITE" | "INDICACAO" | "OUTRO";
            valorEstimado?: number;
            /** @enum {string} */
            status?: "NOVO" | "EM_CONTATO" | "PROPOSTA_ENVIADA" | "EM_NEGOCIACAO" | "GANHO" | "PERDIDO";
            observacoes?: string;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: date-time */
            atualizadoEm?: string;
        };
        ClienteDocumentoInputDTO: {
            nome?: string;
            tipo?: string;
            url?: string;
        };
        ClienteEnderecoInputDTO: {
            rua?: string;
            numero?: string;
            complemento?: string;
            bairro?: string;
            cidade?: string;
            estado?: string;
            cep?: string;
        };
        EditarClienteInputDTO: {
            cnpjCpf?: string;
            nomeRazaoSocial?: string;
            /** @enum {string} */
            tipo: "ESPORADICO" | "RECORRENTE";
            telefone?: string;
            email?: string;
            observacoes?: string;
            /** @enum {string} */
            status: "ATIVO" | "INATIVO";
            /** Format: date */
            dataUltimoServico?: string;
            enderecos: components["schemas"]["ClienteEnderecoInputDTO"][];
            documentos?: components["schemas"]["ClienteDocumentoInputDTO"][];
        };
        ClienteDocumentoResponseDTO: {
            /** Format: uuid */
            id?: string;
            nome?: string;
            tipo?: string;
            url?: string;
        };
        ClienteEnderecoResponseDTO: {
            /** Format: uuid */
            id?: string;
            rua?: string;
            numero?: string;
            complemento?: string;
            bairro?: string;
            cidade?: string;
            estado?: string;
            cep?: string;
        };
        ClienteResponseDTO: {
            /** Format: uuid */
            id?: string;
            cnpjCpf?: string;
            nomeRazaoSocial?: string;
            /** @enum {string} */
            tipo?: "ESPORADICO" | "RECORRENTE";
            telefone?: string;
            email?: string;
            observacoes?: string;
            /** @enum {string} */
            status?: "ATIVO" | "INATIVO";
            /** Format: date */
            dataUltimoServico?: string;
            enderecos?: components["schemas"]["ClienteEnderecoResponseDTO"][];
            documentos?: components["schemas"]["ClienteDocumentoResponseDTO"][];
            cidade?: string;
            estado?: string;
        };
        RedefinirSenhaInputDTO: {
            email?: string;
        };
        LoginUsuarioInputDTO: {
            email: string;
            senha: string;
        };
        LoginUsuarioResponseDTO: {
            usuario?: components["schemas"]["UsuarioResponseDTO"];
            token: string;
        };
        CadastrarUsuarioInputDTO: {
            nomeCompleto?: string;
            email?: string;
            cpf?: string;
            senha?: string;
            /** @enum {string} */
            perfil: "ADMINISTRATIVO" | "TECNICO" | "CLIENTE";
            /** @enum {string} */
            status?: "ATIVO" | "INATIVO";
        };
        CadastrarLeadInputDTO: {
            nome?: string;
            empresa?: string;
            email?: string;
            telefone?: string;
            /** @enum {string} */
            origem: "GOOGLE" | "FACEBOOK" | "INSTAGRAM" | "WEBSITE" | "INDICACAO" | "OUTRO";
            valorEstimado: number;
            /** @enum {string} */
            status?: "NOVO" | "EM_CONTATO" | "PROPOSTA_ENVIADA" | "EM_NEGOCIACAO" | "GANHO" | "PERDIDO";
            observacoes?: string;
        };
        CadastrarClienteInputDTO: {
            cnpjCpf?: string;
            nomeRazaoSocial?: string;
            /** @enum {string} */
            tipo: "ESPORADICO" | "RECORRENTE";
            telefone?: string;
            email?: string;
            observacoes?: string;
            /** @enum {string} */
            status: "ATIVO" | "INATIVO";
            enderecos: components["schemas"]["ClienteEnderecoInputDTO"][];
            documentos?: components["schemas"]["ClienteDocumentoInputDTO"][];
        };
        AtualizarLeadStatusInputDTO: {
            /** @enum {string} */
            status: "NOVO" | "EM_CONTATO" | "PROPOSTA_ENVIADA" | "EM_NEGOCIACAO" | "GANHO" | "PERDIDO";
        };
        PaginatedResponseDTOUsuarioResponseDTO: {
            nodes?: components["schemas"]["UsuarioResponseDTO"][];
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PaginatedResponseDTOLeadResponseDTO: {
            nodes?: components["schemas"]["LeadResponseDTO"][];
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        LeadDashboardDTO: {
            /** Format: int64 */
            totalLeads?: number;
            /** Format: int64 */
            leadsAtivos?: number;
            /** Format: double */
            taxaConversao?: number;
            valorPotencial?: number;
            valorFechado?: number;
        };
        PaginatedResponseDTOClienteResponseDTO: {
            nodes?: components["schemas"]["ClienteResponseDTO"][];
            hasNextPage?: boolean;
            hasPreviousPage?: boolean;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ClienteDashboardDTO: {
            /** Format: int64 */
            clientesAtivos?: number;
            /** Format: int64 */
            clientesFixos?: number;
            /** Format: int64 */
            clientesEsporadicos?: number;
            /** Format: int64 */
            totalClientes?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarUsuarioInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioResponseDTO"];
                };
            };
        };
    };
    obterPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponseDTO"];
                };
            };
        };
    };
    editar_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarLeadInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponseDTO"];
                };
            };
        };
    };
    excluir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obterPorId_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
        };
    };
    editar_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarClienteInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
        };
    };
    excluir_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    redefinirSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenhaInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUsuarioInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginUsuarioResponseDTO"];
                };
            };
        };
    };
    cadastrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastrarUsuarioInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioResponseDTO"];
                };
            };
        };
    };
    obterTodos: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                searchText?: string;
                status?: "NOVO" | "EM_CONTATO" | "PROPOSTA_ENVIADA" | "EM_NEGOCIACAO" | "GANHO" | "PERDIDO";
                origem?: "GOOGLE" | "FACEBOOK" | "INSTAGRAM" | "WEBSITE" | "INDICACAO" | "OUTRO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginatedResponseDTOLeadResponseDTO"];
                };
            };
        };
    };
    cadastrar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastrarLeadInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponseDTO"];
                };
            };
        };
    };
    obterTodos_1: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                searchText?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginatedResponseDTOClienteResponseDTO"];
                };
            };
        };
    };
    cadastrar_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastrarClienteInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteResponseDTO"];
                };
            };
        };
    };
    atualizarStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarLeadStatusInputDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadResponseDTO"];
                };
            };
        };
    };
    obterTodosUsuarios: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                searchText?: string;
                perfil?: "ADMINISTRATIVO" | "TECNICO" | "CLIENTE";
                status?: "ATIVO" | "INATIVO";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginatedResponseDTOUsuarioResponseDTO"];
                };
            };
        };
    };
    obterUsuarioPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioResponseDTO"];
                };
            };
        };
    };
    obterDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LeadDashboardDTO"];
                };
            };
        };
    };
    obterDashboard_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClienteDashboardDTO"];
                };
            };
        };
    };
    excluir_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
