import type { VariantProps } from "tailwind-variants";
import { tv } from "tailwind-variants";

export const style = tv({
  base: "",
  variants: {
    size: {
      none: "mb-0",
      "2xs": "mb-2xs",
      xs: "mb-xs",
      sm: "mb-sm",
      md: "mb-md",
      lg: "mb-lg",
      xl: "mb-xl",
      "2xl": "mb-2xl",
      "3xl": "mb-3xl",
      "4xl": "mb-4xl",
      "5xl": "mb-5xl",
      "6xl": "mb-6xl",
      "7xl": "mb-7xl",
      "8xl": "mb-8xl",
      "9xl": "mb-9xl",
      "10xl": "mb-10xl",
      "11xl": "mb-11xl",
      "12xl": "mb-12xl",
    },
    sm: {
      none: "sm:mb-0",
      "2xs": "sm:mb-2xs",
      xs: "sm:mb-xs",
      sm: "sm:mb-sm",
      md: "sm:mb-md",
      lg: "sm:mb-lg",
      xl: "sm:mb-xl",
      "2xl": "sm:mb-2xl",
      "3xl": "sm:mb-3xl",
      "4xl": "sm:mb-4xl",
      "5xl": "sm:mb-5xl",
      "6xl": "sm:mb-6xl",
      "7xl": "sm:mb-7xl",
      "8xl": "sm:mb-8xl",
      "9xl": "sm:mb-9xl",
      "10xl": "sm:mb-10xl",
      "11xl": "sm:mb-11xl",
      "12xl": "sm:mb-12xl",
    },
    md: {
      none: "md:mb-0",
      "2xs": "md:mb-2xs",
      xs: "md:mb-xs",
      sm: "md:mb-sm",
      md: "md:mb-md",
      lg: "md:mb-lg",
      xl: "md:mb-xl",
      "2xl": "md:mb-2xl",
      "3xl": "md:mb-3xl",
      "4xl": "md:mb-4xl",
      "5xl": "md:mb-5xl",
      "6xl": "md:mb-6xl",
      "7xl": "md:mb-7xl",
      "8xl": "md:mb-8xl",
      "9xl": "md:mb-9xl",
      "10xl": "md:mb-10xl",
      "11xl": "md:mb-11xl",
      "12xl": "md:mb-12xl",
    },
    lg: {
      none: "lg:mb-0",
      "2xs": "lg:mb-2xs",
      xs: "lg:mb-xs",
      sm: "lg:mb-sm",
      md: "lg:mb-md",
      lg: "lg:mb-lg",
      xl: "lg:mb-xl",
      "2xl": "lg:mb-2xl",
      "3xl": "lg:mb-3xl",
      "4xl": "lg:mb-4xl",
      "5xl": "lg:mb-5xl",
      "6xl": "lg:mb-6xl",
      "7xl": "lg:mb-7xl",
      "8xl": "lg:mb-8xl",
      "9xl": "lg:mb-9xl",
      "10xl": "lg:mb-10xl",
      "11xl": "lg:mb-11xl",
      "12xl": "lg:mb-12xl",
    },
    xl: {
      none: "xl:mb-0",
      "2xs": "xl:mb-2xs",
      xs: "xl:mb-xs",
      sm: "xl:mb-sm",
      md: "xl:mb-md",
      lg: "xl:mb-lg",
      xl: "xl:mb-xl",
      "2xl": "xl:mb-2xl",
      "3xl": "xl:mb-3xl",
      "4xl": "xl:mb-4xl",
      "5xl": "xl:mb-5xl",
      "6xl": "xl:mb-6xl",
      "7xl": "xl:mb-7xl",
      "8xl": "xl:mb-8xl",
      "9xl": "xl:mb-9xl",
      "10xl": "xl:mb-10xl",
      "11xl": "xl:mb-11xl",
      "12xl": "xl:mb-12xl",
    },
    "2xl": {
      none: "2xl:mb-0",
      "2xs": "2xl:mb-2xs",
      xs: "2xl:mb-xs",
      sm: "2xl:mb-sm",
      md: "2xl:mb-md",
      lg: "2xl:mb-lg",
      xl: "2xl:mb-xl",
      "2xl": "2xl:mb-2xl",
      "3xl": "2xl:mb-3xl",
      "4xl": "2xl:mb-4xl",
      "5xl": "2xl:mb-5xl",
      "6xl": "2xl:mb-6xl",
      "7xl": "2xl:mb-7xl",
      "8xl": "2xl:mb-8xl",
      "9xl": "2xl:mb-9xl",
      "10xl": "2xl:mb-10xl",
      "11xl": "2xl:mb-11xl",
      "12xl": "2xl:mb-12xl",
    },
  },
  defaultVariants: {
    size: "lg",
  },
});

export type StyleVariants = VariantProps<typeof style>;
